# Generated by Django 4.1.6 on 2023-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_group_member_membersingroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="date_of_adding",
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
    ]
