# Generated by Django 4.1.6 on 2023-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_group_description_alter_member_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
