# Generated by Django 4.1.6 on 2023-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_member_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
