# Generated by Django 4.1.6 on 2023-04-27 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_member_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="date_of_birth",
        ),
    ]
