# Generated by Django 4.1.6 on 2023-04-28 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_member_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="gender",
        ),
    ]
