# Generated by Django 4.1.6 on 2023-04-29 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_group_owner_alter_member_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
    ]
