# Generated by Django 4.1.6 on 2023-05-12 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_member_date_of_birth_member_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_joined",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
