# Generated by Django 4.1.6 on 2023-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_member_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersingroup",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
