# Generated by Django 4.1.6 on 2023-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_membersingroup_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
